create table Musteri (
	id INT,
	Ad VARCHAR(50),
	Soyad VARCHAR(50),
	Cinsiyet VARCHAR(50),
	Hesap VARCHAR(50)
);
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (1, 'Borden', 'Saull', 'Male', '€88,96');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (2, 'Marcus', 'Iskower', 'Male', '€158,26');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (3, 'Stefanie', 'Cockaday', 'Female', '€386,66');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (4, 'Devlen', 'Ibanez', 'Male', '€383,96');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (5, 'Harbert', 'Coysh', 'Male', '€473,47');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (6, 'Nadya', 'Habens', 'Female', '€205,68');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (7, 'Tobiah', 'Spiller', 'Male', '€111,05');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (8, 'Violette', 'Bourtoumieux', 'Female', '€95,46');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (9, 'Zorana', 'Fontanet', 'Female', '€453,23');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (10, 'Benji', 'Hast', 'Male', '€129,53');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (11, 'Benyamin', 'McKevitt', 'Male', '€284,08');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (12, 'Monah', 'Du Fray', 'Female', '€275,78');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (13, 'Hobard', 'Ziemke', 'Male', '€29,07');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (14, 'Morganica', 'Collocott', 'Female', '€408,06');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (15, 'Juliana', 'Carverhill', 'Female', '€328,94');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (16, 'Bevan', 'Fuller', 'Male', '€275,38');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (17, 'Erskine', 'Starbeck', 'Male', '€347,60');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (18, 'Hendrika', 'Vasilyev', 'Female', '€88,21');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (19, 'Kellia', 'Rockhill', 'Female', '€485,28');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (20, 'Melli', 'Ber', 'Female', '€302,30');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (21, 'Cassie', 'Duplan', 'Male', '€366,20');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (22, 'Noak', 'Bunclark', 'Male', '€391,31');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (23, 'Melisandra', 'Calvie', 'Female', '€122,32');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (24, 'Naomi', 'Meneer', 'Female', '€78,48');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (25, 'Prinz', 'Baser', 'Male', '€495,59');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (26, 'Bastian', 'Hackford', 'Male', '€17,38');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (27, 'Ellene', 'Daouze', 'Female', '€441,48');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (28, 'Chaunce', 'Petican', 'Male', '€463,72');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (29, 'Buck', 'Antognetti', 'Male', '€341,60');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (30, 'Sibylla', 'Tithecote', 'Female', '€341,91');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (31, 'Valenka', 'Fransman', 'Female', '€279,89');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (32, 'Tito', 'MacFadden', 'Male', '€260,08');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (33, 'Consolata', 'Millward', 'Female', '€77,83');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (34, 'Pace', 'Hatrey', 'Male', '€287,90');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (35, 'Devlen', 'Drakeley', 'Male', '€351,94');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (36, 'Anthia', 'Ragbourn', 'Female', '€230,10');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (37, 'Dody', 'Vaskin', 'Female', '€73,79');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (38, 'Reynold', 'Cholton', 'Male', '€163,83');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (39, 'Avrom', 'Andrusyak', 'Male', '€32,22');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (40, 'Sharl', 'Lyfe', 'Female', '€235,44');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (41, 'Nefen', 'McDermot', 'Male', '€490,84');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (42, 'Si', 'Melior', 'Male', '€316,60');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (43, 'Ellyn', 'Flament', 'Female', '€215,35');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (44, 'Moss', 'Kegg', 'Male', '€395,05');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (45, 'Gwen', 'Dainter', 'Female', '€292,73');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (46, 'Paul', 'Thurlow', 'Male', '€181,81');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (47, 'Emmi', 'Jantzen', 'Female', '€118,67');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (48, 'Marne', 'Labin', 'Female', '€495,07');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (49, 'Jody', 'Lupton', 'Female', '€379,74');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (50, 'Sallee', 'Kensy', 'Female', '€239,46');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (51, 'Irwin', 'Pietzner', 'Male', '€19,06');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (52, 'Galen', 'Bosenworth', 'Male', '€283,56');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (53, 'Ilene', 'Kirke', 'Female', '€248,41');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (54, 'Fanni', 'Geill', 'Female', '€458,23');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (55, 'Thurstan', 'Giottini', 'Male', '€18,86');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (56, 'Anallese', 'Ungaretti', 'Female', '€173,66');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (57, 'Les', 'Kilgrove', 'Male', '€182,77');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (58, 'Toby', 'Kuzemka', 'Female', '€153,02');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (59, 'Llewellyn', 'Eskrick', 'Male', '€46,62');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (60, 'Woody', 'Gamon', 'Male', '€167,19');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (61, 'Ludwig', 'Ropkes', 'Male', '€343,19');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (62, 'Rafaello', 'Diem', 'Male', '€354,36');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (63, 'Floria', 'Mc Grath', 'Female', '€247,87');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (64, 'Constantia', 'Sprott', 'Female', '€218,58');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (65, 'Anastasia', 'La Vigne', 'Female', '€315,07');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (66, 'Rhetta', 'Huyton', 'Female', '€386,46');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (67, 'Brandy', 'Cranstone', 'Male', '€44,34');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (68, 'Bone', 'Tourle', 'Male', '€374,76');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (69, 'Sonia', 'Feavyour', 'Female', '€74,40');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (70, 'Sharl', 'Warret', 'Female', '€310,15');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (71, 'Noell', 'Baskwell', 'Female', '€364,99');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (72, 'Petra', 'Poole', 'Female', '€355,06');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (73, 'Fredericka', 'McSporon', 'Female', '€193,89');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (74, 'Jewell', 'D''eathe', 'Female', '€243,49');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (75, 'Ilyse', 'Regina', 'Female', '€215,98');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (76, 'Pietro', 'Pettegre', 'Male', '€49,44');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (77, 'Kin', 'Barwick', 'Male', '€219,56');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (78, 'Urbain', 'Ech', 'Male', '€24,97');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (79, 'Appolonia', 'Godrich', 'Female', '€310,43');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (80, 'Robbyn', 'MacGebenay', 'Female', '€457,28');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (81, 'Trula', 'Caddell', 'Female', '€318,68');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (82, 'Alyssa', 'Yurinov', 'Female', '€244,73');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (83, 'Simonne', 'Shepton', 'Female', '€254,73');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (84, 'Boyd', 'Scothorne', 'Male', '€293,53');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (85, 'Antin', 'Janku', 'Male', '€477,29');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (86, 'Hyacinth', 'Gullefant', 'Female', '€208,48');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (87, 'Mignon', 'Hanhart', 'Female', '€61,35');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (88, 'Cyndie', 'Pullinger', 'Female', '€103,80');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (89, 'Minta', 'McNay', 'Female', '€165,36');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (90, 'Lucho', 'Pacht', 'Male', '€303,66');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (91, 'Harald', 'Mc Kellen', 'Male', '€297,07');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (92, 'Bird', 'Tidcomb', 'Female', '€212,25');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (93, 'Robert', 'McGurk', 'Male', '€136,07');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (94, 'Reagan', 'Tomasutti', 'Male', '€391,62');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (95, 'Jacquenetta', 'Brizland', 'Female', '€441,19');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (96, 'Sophey', 'Onslow', 'Female', '€178,49');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (97, 'Ferdinand', 'Lauritsen', 'Male', '€192,79');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (98, 'Michele', 'Milnes', 'Male', '€154,30');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (99, 'Addie', 'Scotter', 'Male', '€276,91');
insert into Musteri (id, Ad, Soyad, Cinsiyet, Hesap) values (100, 'Kellen', 'Gilcrist', 'Female', '€168,99');
